# 1. Create a 3x3x3 array with random values 

In [164]:
import numpy as np
array = np.random.randint(100,size=(3,3,3))
print(f"array dimension : {array.ndim} and shape : {array.shape}\n")
print(array)  

array dimension : 3 and shape : (3, 3, 3)

[[[31 12 13]
  [35 54  8]
  [20 42  9]]

 [[94 69 17]
  [67 78 45]
  [95 85 52]]

 [[58 21 37]
  [44 65 88]
  [37 41 58]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [210]:
import numpy as np
Z = np.matrix(np.diag([1,2,3,4],k=-1))
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [211]:
import numpy as np
checkerboard_pattern = np.matrix(np.zeros(shape=(8,8),dtype=int))
checkerboard_pattern[::2,1::2]=1
checkerboard_pattern[1::2,::2]=1
print(checkerboard_pattern)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [221]:
import numpy as np
array = np.matrix(np.random.randint(100,size=(5,5)))
array_max,array_min = array.max(),array.min()
print(array,"\n")
array = (array-array_min)/(array_max-array_min)
print("after normalize matrix will be:\n\n",array)



[[82 71 26 20  6]
 [29 83 33 74 57]
 [ 1 42 93 11 64]
 [42 22 77  0 68]
 [94 50 85 20 91]] 

after normalize matrix will be:

 [[0.87234043 0.75531915 0.27659574 0.21276596 0.06382979]
 [0.30851064 0.88297872 0.35106383 0.78723404 0.60638298]
 [0.0106383  0.44680851 0.9893617  0.11702128 0.68085106]
 [0.44680851 0.23404255 0.81914894 0.         0.72340426]
 [1.         0.53191489 0.90425532 0.21276596 0.96808511]]


# 5.  How to find common values between two arrays?

In [233]:
import numpy as np
array1 = np.random.randint(20,size=(3,3))
array2 = np.random.randint(20,size=(3,6))
common_value = np.intersect1d(array1,array2)
print(f"array 1 is : \n {array1}\n\n array 2 is : \n{array2}\n\n common value between two arrays is : \n {common_value}")

array 1 is : 
 [[14 15  1]
 [ 6 16  9]
 [ 1 14  0]]

 array 2 is : 
[[10  9  6  9 17  2]
 [ 6 10  6 12 10  0]
 [18 19 14  7 15  0]]

 common value between two arrays is : 
 [ 0  6  9 14 15]


# 6.How to get the dates of yesterday, today and tomorrow?

In [266]:
import numpy as np
import pandas as pd
today = np.datetime64('today')
yesterday = today-1
tomorrow = today+1
dates = pd.DataFrame(np.array([yesterday,today,tomorrow]).reshape(1,3),index=["dates"],columns=["yesterday","today","tomorrow"])
dates

yesterday      today   tomorrow
dates 2020-07-29 2020-07-30 2020-07-31

# 7. Consider two random array A and B, check if they are equal

In [280]:
import numpy as np
array1 = np.random.randint(20,size=(3,3))
array2 = np.random.randint(20,size=(3,3))
equal = np.equal(array1,array2)
print(array1,"\n")
print(array2,"\n")

if equal.all():
    print("array is equal")
else:
    print("array not equal")

[[ 4  7 12]
 [ 3  5  8]
 [10  6  9]] 

[[15 10 15]
 [ 0  9 13]
 [ 6  5 10]] 

array not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [316]:
import numpy as np
v = np.random.randint(100,size=10)
print("before vector view:")
print(v)
v[np.argmax(v)] = 0
print("\n after replace 0 in maximum value place then vector view:")
print(v)

before vector view:
[ 7 67 45 29 50 17 60 37 54 86]

 after replace 0 in maximum value place then vector view:
[ 7 67 45 29 50 17 60 37 54  0]


# 9. How to print all the values of an array?

In [317]:
import numpy as np
A = np.arange(25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 10.Subtract the mean of each row of a matrix

In [325]:
import numpy as np
A = np.matrix(np.random.randint(100,size=(5,5)))
print(A,"\n\n")
print("after perform the opration:\n")
m = A - A.mean(axis=1)
m

[[48 13 18 75 11]
 [50 35 59 10 43]
 [45 19 65 82 95]
 [59 76 29 89 31]
 [36 71 99 34 16]] 


after perform the opration:



matrix([[ 15. , -20. , -15. ,  42. , -22. ],
        [ 10.6,  -4.4,  19.6, -29.4,   3.6],
        [-16.2, -42.2,   3.8,  20.8,  33.8],
        [  2.2,  19.2, -27.8,  32.2, -25.8],
        [-15.2,  19.8,  47.8, -17.2, -35.2]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [327]:
import numpy as np
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
Z+= np.bincount(I,minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 7 7 2 6 2 7 6 2 2 1 0 3 7 8 3 3 8 7 7]
[2. 2. 5. 4. 2. 1. 3. 7. 3. 1.]


# 12.How to get the diagonal of a dot product?

In [346]:
import numpy as np
m1 = np.matrix(np.random.randint(100,size=(5,5)))
print(m1,"\n\n")
m2 = np.matrix(np.random.randint(100,size=(5,5)))
print(m2,"\n\n")
print(np.diag(np.dot(m1,m2)),"\n\n")

[[77 15 37 53 93]
 [36 27 43 85 50]
 [87 59 71 16 20]
 [35 94 92 90 23]
 [33 45 29 80 87]] 


[[14  8 30 89  4]
 [55 52 23 92 37]
 [98 84 73 15  8]
 [ 5 23  0 12 42]
 [13  2 56 64 51]] 


[ 7003  7359 10270 15695  9826] 




# 13.How to find the most frequent value in an array?

In [373]:
import numpy as np
from statistics import mode
a = np.array([1,2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,3,4,2,2,4,6,4,6])
mode(a)

1

# 14.How to get the n largest values of an array

In [388]:
import numpy as np
m1 = np.array(np.random.randint(100,size=10))
print(m1)
print(np.sort(m1))
print(m1.max())

[62 98 59 22 97 93 18 46 40 91]
[18 22 40 46 59 62 91 93 97 98]
98


# 15.How to create a record array from a regular array?

In [407]:
import numpy as np
a1 = np.arange(1,5)
a2 = np.array(["a","b","c","d"])
print(np.core.records.fromarrays([a1,a2]))

[(1, 'a') (2, 'b') (3, 'c') (4, 'd')]
